spring:   
  datasource:
  #  url: jdbc:mysql://rm-wz92q1p5904s5wjo5.mysql.rds.aliyuncs.com:3306/qcx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://120.76.190.81:3306/qcx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: jky
  #  password: GZzxtVS123jky2017
    password: GZjky01001
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
          max-wait: 3000
          max-idle: 20 #最大空闲连接:连接池中容许保持空闲状态的最大连接数量,超过的空闲连接将被释放,如果设置为负数表示不限制
          min-idle: 10 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,低于这个数量将创建新的连接,如果设置为0则不创建
          max-active: 20    #最大活动连接:连接池在同一时间能够分配的最大活动连接的数量, 如果设置为非正数则表示不限制
          validation-query: SELECT 1 #用来验证从连接池取出的连接,在将连接返回给调用者之前.如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
          test-on-borrow: true #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个.
          test-on-connect: true
          test-while-idle: true #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
          remove-abandoned: true
          remove-abandoned-timeout: 180
          time-between-eviction-runs-millis: 300000  #以毫秒为单位 ，空闲连接回收的时间间隔，与test-while-idle一起使用，设置为5分钟
          num-tests-per-eviction-run: 20  #在每次空闲连接回收器线程(如果有)运行时检查的连接数量，最好和maxActive一致
          min-evictable-idle-time-millis: 1800000 #连接池空闲连接的有效时间 ，设置30分钟